name: 'PR Label Checker'
on:
  pull_request:
    branches:
      - main
    types:
      - reopened
      - labeled
      - unlabeled
jobs:
  check_labels:
    name: 'Check PR Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          only_status: waiting
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'