name: 'PR Label Checker'
on:
  pull_request:
    branches:
      - main
    types:
      - reopened
      - labeled
      - unlabeled
      - ready_for_review
jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{github.token }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'