name: 'PR Workflow'
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - edited
      - ready_for_review
      - labeled
      - reopened


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: init-step
        uses: actions/setup-node@v3
        with:
            node-version: 16
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          only_status: waiting
  pr-validation:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
      - uses: fadi-quader-mox/pr-version-bump@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
